[env]
# Postgres built-in env vars
PGDATA = "tmp/postgres"
PGUSER = "postgres"
# Custom database env vars
POSTGRES_USER = "postgres"
POSTGRES_DB = "tunez_dev"
# Keep iex history
ERL_AFLAGS = "-kernel shell_history enabled"
